# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(395, 262)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(SettingsDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 371, 201))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 30, 351, 161))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.modArchivePathLineEdit = QtWidgets.QLineEdit(self.widget)
        self.modArchivePathLineEdit.setObjectName("modArchivePathLineEdit")
        self.gridLayout.addWidget(self.modArchivePathLineEdit, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.tmpPathLineEdit = QtWidgets.QLineEdit(self.widget)
        self.tmpPathLineEdit.setObjectName("tmpPathLineEdit")
        self.gridLayout.addWidget(self.tmpPathLineEdit, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.tmpPathBrowseButton = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.tmpPathBrowseButton.setIcon(icon)
        self.tmpPathBrowseButton.setObjectName("tmpPathBrowseButton")
        self.gridLayout.addWidget(self.tmpPathBrowseButton, 5, 1, 1, 1)
        self.archivePathBrowseButton = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.archivePathBrowseButton.setIcon(icon)
        self.archivePathBrowseButton.setObjectName("archivePathBrowseButton")
        self.gridLayout.addWidget(self.archivePathBrowseButton, 1, 1, 1, 1)
        self.modInstallPathLineEdit = QtWidgets.QLineEdit(self.widget)
        self.modInstallPathLineEdit.setObjectName("modInstallPathLineEdit")
        self.gridLayout.addWidget(self.modInstallPathLineEdit, 3, 0, 1, 1)
        self.installPathBrowseButton = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.installPathBrowseButton.setIcon(icon)
        self.installPathBrowseButton.setObjectName("installPathBrowseButton")
        self.gridLayout.addWidget(self.installPathBrowseButton, 3, 1, 1, 1)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        self.archivePathBrowseButton.clicked.connect(SettingsDialog.browseArchivePath)
        self.installPathBrowseButton.clicked.connect(SettingsDialog.browseInstallPath)
        self.tmpPathBrowseButton.clicked.connect(SettingsDialog.browseTmpPath)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.groupBox.setTitle(_translate("SettingsDialog", "Paths"))
        self.modArchivePathLineEdit.setText(_translate("SettingsDialog", "~/.modlink/archive"))
        self.label_4.setText(_translate("SettingsDialog", "Tmp Directory"))
        self.tmpPathLineEdit.setText(_translate("SettingsDialog", "~/.modlink/tmp"))
        self.label_2.setText(_translate("SettingsDialog", "Mod Archive Path"))
        self.label_3.setText(_translate("SettingsDialog", "Mod Install Path"))
        self.tmpPathBrowseButton.setText(_translate("SettingsDialog", "Browse"))
        self.archivePathBrowseButton.setText(_translate("SettingsDialog", "Browse"))
        self.modInstallPathLineEdit.setText(_translate("SettingsDialog", "~/.modlink/install"))
        self.installPathBrowseButton.setText(_translate("SettingsDialog", "Browse"))
